{% set name = "napari-plugin-engine" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48239476b13a21a31bb08e4fe21cb192afba717464bdce9e21ac2fbafed20e96

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6

test:
  imports:
    - napari_plugin_engine

about:
  home: https://github.com/napari/napari-plugin-engine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of pluggy - plugin management package

  # The remaining entries in this section are optional, but recommended.
  description: |
    A fork of pluggy - plugin management package.
  doc_url: https://napari-plugin-engine.readthedocs.io/
  dev_url: https://github.com/napari/napari-plugin-engine

extra:
  recipe-maintainers:
    - tlambert03
    - jni
    - sofroniewn
