{% set name = "napari-plugin-engine" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 46829cf02f368c8f2f1aa8b998ec73bcf14a2c1f5c15abd94b82154d7aef510d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - importlib-metadata >=1.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - napari_plugin_engine

about:
  home: https://github.com/napari/napari-plugin-engine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of pluggy - plugin management package

  # The remaining entries in this section are optional, but recommended.
  description: |
    A fork of pluggy - plugin management package.
  doc_url: https://napari-plugin-engine.readthedocs.io/
  dev_url: https://github.com/napari/napari-plugin-engine

extra:
  recipe-maintainers:
    - DragaDoncila
    - tlambert03
    - jni
    - sofroniewn
