{% set name = "napari-plugin-engine" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa926f869d70e0d652c005661948cd0c7fee5508ae17d437937f34f5287590b3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - importlib-metadata >=1.5  # [py<38]

test:
  imports:
    - napari_plugin_engine

about:
  home: https://github.com/napari/napari-plugin-engine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of pluggy - plugin management package

  # The remaining entries in this section are optional, but recommended.
  description: |
    A fork of pluggy - plugin management package.
  doc_url: https://napari-plugin-engine.readthedocs.io/
  dev_url: https://github.com/napari/napari-plugin-engine

extra:
  recipe-maintainers:
    - tlambert03
    - jni
    - sofroniewn
